"""crm notes transcript consent

Revision ID: f16f3eefb70b
Revises: ec822fc17325
Create Date: 2026-07-07 10:58:58.356525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16f3eefb70b'
down_revision: Union[str, None] = 'ec822fc17325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('customer_user_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_notes_customer_user_id'), 'customer_notes', ['customer_user_id'], unique=False)
    op.create_index(op.f('ix_customer_notes_org_id'), 'customer_notes', ['org_id'], unique=False)
    # server_default so the NOT NULL column applies cleanly to the live Neon
    # DB's existing rows (everyone starts opted out — consent is explicit).
    op.add_column(
        'users',
        sa.Column('transcript_consent', sa.Boolean(), nullable=False,
                  server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'transcript_consent')
    op.drop_index(op.f('ix_customer_notes_org_id'), table_name='customer_notes')
    op.drop_index(op.f('ix_customer_notes_customer_user_id'), table_name='customer_notes')
    op.drop_table('customer_notes')
    # ### end Alembic commands ###
