"""content posts

Revision ID: d6ee21f9bf1c
Revises: 6aae47b8b3ce
Create Date: 2026-07-07 02:54:33.052141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6ee21f9bf1c'
down_revision: Union[str, None] = '6aae47b8b3ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('media_key', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'platform', name='uq_content_day_platform')
    )
    op.create_index(op.f('ix_content_posts_day'), 'content_posts', ['day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_posts_day'), table_name='content_posts')
    op.drop_table('content_posts')
    # ### end Alembic commands ###
