"""org billing subscriptions

Revision ID: 35ff1a0bb2fe
Revises: f16f3eefb70b
Create Date: 2026-07-07 11:06:17.373088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35ff1a0bb2fe'
down_revision: Union[str, None] = 'f16f3eefb70b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default so existing org rows migrate cleanly ("trial" keeps
    # their features on); a named unique INDEX instead of the autogenerated
    # unnamed constraint, which SQLite cannot ALTER in.
    op.add_column(
        'orgs',
        sa.Column('billing_status', sa.String(), nullable=False, server_default='trial'),
    )
    op.add_column('orgs', sa.Column('razorpay_subscription_id', sa.String(), nullable=True))
    op.add_column('orgs', sa.Column('billing_updated_at', sa.DateTime(), nullable=True))
    op.create_index(
        'uq_orgs_razorpay_subscription_id', 'orgs', ['razorpay_subscription_id'], unique=True
    )


def downgrade() -> None:
    op.drop_index('uq_orgs_razorpay_subscription_id', table_name='orgs')
    op.drop_column('orgs', 'billing_updated_at')
    op.drop_column('orgs', 'razorpay_subscription_id')
    op.drop_column('orgs', 'billing_status')
