"""temple partnerships notifications

Revision ID: 0de89516efbb
Revises: 59f7c916f184
Create Date: 2026-07-07 10:36:14.486511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de89516efbb'
down_revision: Union[str, None] = '59f7c916f184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('dedupe_key', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'dedupe_key', 'phone', name='uq_notification_once')
    )
    op.create_index(op.f('ix_notification_log_dedupe_key'), 'notification_log', ['dedupe_key'], unique=False)
    op.create_table('temple_festivals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temple_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_ml', sa.String(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temple_festivals_day'), 'temple_festivals', ['day'], unique=False)
    op.create_index(op.f('ix_temple_festivals_temple_id'), 'temple_festivals', ['temple_id'], unique=False)
    op.create_table('temple_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temple_id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temple_partners_slug'), 'temple_partners', ['slug'], unique=True)
    op.create_index(op.f('ix_temple_partners_temple_id'), 'temple_partners', ['temple_id'], unique=True)
    op.create_table('temple_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('temple_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone', 'temple_id', name='uq_subscription_phone_temple')
    )
    op.create_index(op.f('ix_temple_subscriptions_phone'), 'temple_subscriptions', ['phone'], unique=False)
    op.create_index(op.f('ix_temple_subscriptions_temple_id'), 'temple_subscriptions', ['temple_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temple_subscriptions_temple_id'), table_name='temple_subscriptions')
    op.drop_index(op.f('ix_temple_subscriptions_phone'), table_name='temple_subscriptions')
    op.drop_table('temple_subscriptions')
    op.drop_index(op.f('ix_temple_partners_temple_id'), table_name='temple_partners')
    op.drop_index(op.f('ix_temple_partners_slug'), table_name='temple_partners')
    op.drop_table('temple_partners')
    op.drop_index(op.f('ix_temple_festivals_temple_id'), table_name='temple_festivals')
    op.drop_index(op.f('ix_temple_festivals_day'), table_name='temple_festivals')
    op.drop_table('temple_festivals')
    op.drop_index(op.f('ix_notification_log_dedupe_key'), table_name='notification_log')
    op.drop_table('notification_log')
    # ### end Alembic commands ###
