"""orgs tenancy users org_id

Revision ID: ab1efa9680db
Revises: 0de89516efbb
Create Date: 2026-07-07 10:44:07.867392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1efa9680db'
down_revision: Union[str, None] = '0de89516efbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo_key', sa.String(), nullable=True),
    sa.Column('theme_primary', sa.String(), nullable=False),
    sa.Column('theme_bg', sa.String(), nullable=False),
    sa.Column('persona_overlay', sa.Text(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orgs_handle'), 'orgs', ['handle'], unique=True)
    op.create_index(op.f('ix_orgs_owner_user_id'), 'orgs', ['owner_user_id'], unique=False)
    op.add_column('users', sa.Column('org_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_column('users', 'org_id')
    op.drop_index(op.f('ix_orgs_owner_user_id'), table_name='orgs')
    op.drop_index(op.f('ix_orgs_handle'), table_name='orgs')
    op.drop_table('orgs')
    # ### end Alembic commands ###
