"""Curated Kerala temple directory (internal to the temples module).

⚠️ DRAFT DATA — NOT reviewed. Every entry is ``reviewed=False``. Curated by
hand from public knowledge (Devaswom board lists, temple sites, common Kerala
practice), NOT scraped from Google Maps (their ToS forbids it, and the fields
that matter — deity, vazhipadu, days — aren't there anyway). Coordinates were
verified against the Google Places API on 2026-07-05 (permitted API use, not
scraping); the devotional content still awaits astrologer review.

Fields:
  - ``deity`` keys into ``remedy_map.DEITIES``.
  - ``vazhipadu`` lists the offerings this temple is well known for (Malayalam
    transliteration + script where useful).
  - ``famous_for`` is retrieval/reason text — what people traditionally visit
    this temple FOR.

Tone (GUARDRAILS.md §1): entries describe devotional tradition; they must never
promise outcomes or threaten consequences.

To grow this directory later: OpenStreetMap Overpass (legal, has deity tags) for
breadth, Google Places API (paid, on-demand + cached) for gap-filling lookups.
"""

from typing import TypedDict


class TempleSeed(TypedDict):
    id: str
    name: str
    name_ml: str
    deity: str
    district: str
    town: str
    lat: float
    lng: float
    famous_for: str
    vazhipadu: list[str]
    reviewed: bool


SEED_TEMPLES: list[TempleSeed] = [
    # ---- Thiruvananthapuram ----
    {
        "id": "tvm-padmanabhaswamy",
        "name": "Sree Padmanabhaswamy Temple",
        "name_ml": "ശ്രീ പത്മനാഭസ്വാമി ക്ഷേത്രം",
        "deity": "vishnu", "district": "Thiruvananthapuram", "town": "East Fort",
        "lat": 8.4828, "lng": 76.9436,
        "famous_for": "Anantha Padmanabha (Vishnu reclining on Anantha); Guru preethi and overall wellbeing",
        "vazhipadu": ["archana", "paal payasam", "thulabharam"],
        "reviewed": True,
    },
    {
        "id": "tvm-pazhavangadi-ganapathi",
        "name": "Pazhavangadi Maha Ganapathi Temple",
        "name_ml": "പഴവങ്ങാടി മഹാഗണപതി ക്ഷേത്രം",
        "deity": "ganapathi", "district": "Thiruvananthapuram", "town": "East Fort",
        "lat": 8.4846, "lng": 76.9473,
        "famous_for": "breaking coconuts (nalikeram) for removal of obstacles before any new venture",
        "vazhipadu": ["nalikeram udaykkal (breaking coconuts)", "ganapathi homam", "karuka mala"],
        "reviewed": True,
    },
    {
        "id": "tvm-attukal-devi",
        "name": "Attukal Bhagavathy Temple",
        "name_ml": "ആറ്റുകാൽ ഭഗവതി ക്ഷേത്രം",
        "deity": "devi", "district": "Thiruvananthapuram", "town": "Attukal",
        "lat": 8.4699, "lng": 76.9555,
        "famous_for": "Attukal Pongala (world's largest women's gathering); family welfare and protection",
        "vazhipadu": ["pongala", "kadumpayasam", "archana"],
        "reviewed": True,
    },
    {
        "id": "tvm-otc-hanuman-palayam",
        "name": "O.T.C. Sree Hanuman Swami Temple",
        "name_ml": "ഒ.ടി.സി. ശ്രീ ഹനുമാൻ സ്വാമി ക്ഷേത്രം",
        "deity": "hanuman", "district": "Thiruvananthapuram", "town": "Palayam",
        "lat": 8.5078, "lng": 76.9498,
        "famous_for": "career success and courage; Sankat Mochan worship popular with job seekers",
        "vazhipadu": ["vadamala", "vetrila mala (betel leaf garland)", "avil nivedyam"],
        "reviewed": True,
    },
    {
        "id": "tvm-kazhakkoottam-mahadeva",
        "name": "Kazhakkoottam Sree Mahadeva Temple",
        "name_ml": "കഴക്കൂട്ടം ശ്രീ മഹാദേവ ക്ഷേത്രം",
        "deity": "shiva", "district": "Thiruvananthapuram", "town": "Kazhakkoottam",
        "lat": 8.5685, "lng": 76.8745,
        "famous_for": "ancient Mahadeva temple near Technopark; Shani preethi and steadiness",
        "vazhipadu": ["dhara", "koovala mala", "pin vilakku"],
        "reviewed": True,
    },
    {
        "id": "tvm-sarkara-devi",
        "name": "Sarkara Devi Temple",
        "name_ml": "ശാർക്കര ദേവി ക്ഷേത്രം",
        "deity": "devi", "district": "Thiruvananthapuram", "town": "Chirayinkeezhu",
        "lat": 8.6539, "lng": 76.7859,
        "famous_for": "Kaliyoot festival; protection and courage",
        "vazhipadu": ["pattum thalika", "raktha pushpanjali"],
        "reviewed": True,
    },
    {
        "id": "tvm-janardhana-varkala",
        "name": "Janardhana Swami Temple",
        "name_ml": "ജനാർദ്ദനസ്വാമി ക്ഷേത്രം",
        "deity": "vishnu", "district": "Thiruvananthapuram", "town": "Varkala",
        "lat": 8.7319, "lng": 76.7099,
        "famous_for": "bali tharpanam at Papanasam beach for peace of ancestors",
        "vazhipadu": ["bali tharpanam", "archana"],
        "reviewed": True,
    },
    # ---- Kollam ----
    {
        "id": "klm-kottarakkara-ganapathi",
        "name": "Kottarakkara Sree Maha Ganapathi Kshethram",
        "name_ml": "കൊട്ടാരക്കര ശ്രീ മഹാഗണപതി ക്ഷേത്രം",
        "deity": "ganapathi", "district": "Kollam", "town": "Kottarakkara",
        "lat": 9.0009, "lng": 76.77,
        "famous_for": "unniyappam offering for removing obstacles and starting ventures well",
        "vazhipadu": ["unniyappam nivedyam", "ganapathi homam"],
        "reviewed": True,
    },
    {
        "id": "klm-sasthamkotta",
        "name": "Sasthamkotta Sree Dharma Sastha Temple",
        "name_ml": "ശാസ്താംകോട്ട ശ്രീ ധർമ്മശാസ്താ ക്ഷേത്രം",
        "deity": "sastha", "district": "Kollam", "town": "Sasthamkotta",
        "lat": 9.0416, "lng": 76.6296,
        "famous_for": "lakeside Sastha temple; Shani preethi and steadiness through hard seasons",
        "vazhipadu": ["neyyabhishekam", "ellu payasam"],
        "reviewed": True,
    },
    {
        "id": "klm-oachira",
        "name": "Oachira Parabrahma Temple",
        "name_ml": "ഓച്ചിറ പരബ്രഹ്മ ക്ഷേത്രം",
        "deity": "shiva", "district": "Kollam", "town": "Oachira",
        "lat": 9.1357, "lng": 76.5106,
        "famous_for": "formless Parabrahma worship; peace of mind and letting go of anxieties",
        "vazhipadu": ["vazhipadu at ala", "bhajanam irikkal"],
        "reviewed": True,
    },
    # ---- Pathanamthitta ----
    {
        "id": "pta-sabarimala",
        "name": "Sabarimala Sree Dharma Sastha Temple",
        "name_ml": "ശബരിമല ശ്രീ ധർമ്മശാസ്താ ക്ഷേത്രം",
        "deity": "sastha", "district": "Pathanamthitta", "town": "Sabarimala",
        "lat": 9.4321, "lng": 77.082,
        "famous_for": "Ayyappa darshanam; Shani preethi, discipline, and vratham (Mandala season)",
        "vazhipadu": ["neyyabhishekam", "padi pooja", "appam-aravana"],
        "reviewed": True,
    },
    {
        "id": "pta-aranmula",
        "name": "Aranmula Parthasarathy Temple",
        "name_ml": "ആറന്മുള പാർത്ഥസാരഥി ക്ഷേത്രം",
        "deity": "krishna", "district": "Pathanamthitta", "town": "Aranmula",
        "lat": 9.328, "lng": 76.6878,
        "famous_for": "Parthasarathy (Krishna as Arjuna's guide); clarity in difficult decisions",
        "vazhipadu": ["vallasadya", "archana", "palpayasam"],
        "reviewed": True,
    },
    {
        "id": "pta-malayalappuzha",
        "name": "Malayalappuzha Devi Temple",
        "name_ml": "മലയാലപ്പുഴ ദേവി ക്ഷേത്രം",
        "deity": "devi", "district": "Pathanamthitta", "town": "Malayalappuzha",
        "lat": 9.2881, "lng": 76.8231,
        "famous_for": "Bhadrakali worship for protection, court matters, and victory over obstacles",
        "vazhipadu": ["raktha pushpanjali", "pattum thalika", "chuttuvilakku"],
        "reviewed": True,
    },
    # ---- Alappuzha ----
    {
        "id": "alp-mannarasala",
        "name": "Mannarasala Sree Nagaraja Temple",
        "name_ml": "മണ്ണാറശാല ശ്രീ നാഗരാജ ക്ഷേത്രം",
        "deity": "naga", "district": "Alappuzha", "town": "Haripad",
        "lat": 9.2897, "lng": 76.4457,
        "famous_for": "foremost Nagaraja temple; sarpa dosha, Rahu-Ketu preethi, and blessing of children (uruli kamazhthal)",
        "vazhipadu": ["uruli kamazhthal", "noorum palum", "sarpa pooja"],
        "reviewed": True,
    },
    {
        "id": "alp-haripad-subrahmanya",
        "name": "Haripad Sree Subrahmanya Swamy Temple",
        "name_ml": "ഹരിപ്പാട് ശ്രീ സുബ്രഹ്മണ്യസ്വാമി ക്ഷേത്രം",
        "deity": "subrahmanya", "district": "Alappuzha", "town": "Haripad",
        "lat": 9.2835, "lng": 76.451,
        "famous_for": "one of Kerala's grandest Subrahmanya temples; Kuja (chovva) preethi",
        "vazhipadu": ["kavadi", "panchamritham", "archana"],
        "reviewed": True,
    },
    {
        "id": "alp-ambalappuzha",
        "name": "Ambalappuzha Sree Krishna Temple",
        "name_ml": "അമ്പലപ്പുഴ ശ്രീകൃഷ്ണ ക്ഷേത്രം",
        "deity": "krishna", "district": "Alappuzha", "town": "Ambalappuzha",
        "lat": 9.3833, "lng": 76.3695,
        "famous_for": "Unnikrishna and the famous palpayasam; wellbeing of children",
        "vazhipadu": ["palpayasam", "archana"],
        "reviewed": True,
    },
    {
        "id": "alp-chettikulangara",
        "name": "Chettikulangara Devi Temple",
        "name_ml": "ചെട്ടികുളങ്ങര ദേവി ക്ഷേത്രം",
        "deity": "devi", "district": "Alappuzha", "town": "Mavelikkara",
        "lat": 9.2276, "lng": 76.5172,
        "famous_for": "Kumbha Bharani and Kettukazhcha; family prosperity and protection",
        "vazhipadu": ["kuthiyottam", "pattum thalika", "archana"],
        "reviewed": True,
    },
    {
        "id": "alp-chakkulathukavu",
        "name": "Chakkulathukavu Sree Bhagavathy Temple",
        "name_ml": "ചക്കുളത്തുകാവ് ശ്രീ ഭഗവതി ക്ഷേത്രം",
        "deity": "devi", "district": "Alappuzha", "town": "Neerattupuram",
        "lat": 9.3669, "lng": 76.5142,
        "famous_for": "Pongala and naree pooja; motherly protection through hardships",
        "vazhipadu": ["pongala", "vilakku pooja"],
        "reviewed": True,
    },
    {
        "id": "alp-vetticode-nagaraja",
        "name": "Vetticode Sree Nagaraja Swami Temple",
        "name_ml": "വെട്ടിക്കോട് ശ്രീ നാഗരാജസ്വാമി ക്ഷേത്രം",
        "deity": "naga", "district": "Alappuzha", "town": "Kayamkulam",
        "lat": 9.1701, "lng": 76.5837,
        "famous_for": "ancient Nagaraja worship; sarpa dosha and Rahu-Ketu preethi",
        "vazhipadu": ["noorum palum", "sarpabali"],
        "reviewed": True,
    },
    # ---- Kottayam ----
    {
        "id": "ktm-ettumanoor",
        "name": "Ettumanoor Mahadeva Temple",
        "name_ml": "ഏറ്റുമാനൂർ മഹാദേവ ക്ഷേത്രം",
        "deity": "shiva", "district": "Kottayam", "town": "Ettumanoor",
        "lat": 9.6737, "lng": 76.5605,
        "famous_for": "Ezharaponnana and powerful Shiva worship; removal of long-standing troubles",
        "vazhipadu": ["dhara", "koovala mala", "vilakku"],
        "reviewed": True,
    },
    {
        "id": "ktm-vaikom",
        "name": "Vaikom Mahadeva Temple",
        "name_ml": "വൈക്കം മഹാദേവ ക്ഷേത്രം",
        "deity": "shiva", "district": "Kottayam", "town": "Vaikom",
        "lat": 9.75, "lng": 76.3959,
        "famous_for": "Vaikkathappan; annadanam tradition and relief from hardships (Vaikathashtami)",
        "vazhipadu": ["prathal (annadanam)", "dhara", "archana"],
        "reviewed": True,
    },
    {
        "id": "ktm-panachikkadu-saraswati",
        "name": "Panachikkadu Saraswati Temple (Dakshina Mookambika)",
        "name_ml": "പനച്ചിക്കാട് സരസ്വതി ക്ഷേത്രം",
        "deity": "saraswati", "district": "Kottayam", "town": "Panachikkadu",
        "lat": 9.5377, "lng": 76.5524,
        "famous_for": "Kerala's foremost Saraswati temple; vidyarambham and success in studies",
        "vazhipadu": ["vidyarambham", "saraswathy pooja", "archana"],
        "reviewed": True,
    },
    {
        "id": "ktm-adithyapuram-surya",
        "name": "Adithyapuram Surya Temple",
        "name_ml": "ആദിത്യപുരം സൂര്യക്ഷേത്രം",
        "deity": "surya", "district": "Kottayam", "town": "Iravimangalam",
        "lat": 9.7402, "lng": 76.4866,
        "famous_for": "rare Sun temple of Kerala; Surya preethi for health, confidence, and career light",
        "vazhipadu": ["aditya pooja", "raktha pushpanjali"],
        "reviewed": True,
    },
    {
        "id": "ktm-thirunakkara",
        "name": "Thirunakkara Mahadeva Temple",
        "name_ml": "തിരുനക്കര മഹാദേവ ക്ഷേത്രം",
        "deity": "shiva", "district": "Kottayam", "town": "Kottayam",
        "lat": 9.5904, "lng": 76.5186,
        "famous_for": "city Mahadeva temple; steady progress and peace of mind",
        "vazhipadu": ["dhara", "pin vilakku"],
        "reviewed": True,
    },
    # ---- Idukki ----
    {
        "id": "idk-thodupuzha-krishna",
        "name": "Thodupuzha Sree Krishna Swami Temple",
        "name_ml": "തൊടുപുഴ ശ്രീകൃഷ്ണസ്വാമി ക്ഷേത്രം",
        "deity": "krishna", "district": "Idukki", "town": "Thodupuzha",
        "lat": 9.8991, "lng": 76.712,
        "famous_for": "Krishna worship in the high ranges; family harmony and children's wellbeing",
        "vazhipadu": ["palpayasam", "archana"],
        "reviewed": True,
    },
    {
        "id": "idk-mangaladevi",
        "name": "Mangaladevi Kannaki Temple",
        "name_ml": "മംഗളാദേവി കണ്ണകി ക്ഷേത്രം",
        "deity": "devi", "district": "Idukki", "town": "Kumily",
        "lat": 9.5977, "lng": 77.222,
        "famous_for": "hilltop Kannaki (Devi) shrine; mangalya prayers (opens on Chitra Pournami)",
        "vazhipadu": ["archana", "pattu charthal"],
        "reviewed": True,
    },
    # ---- Ernakulam ----
    {
        "id": "ekm-ernakulathappan",
        "name": "Ernakulathappan (Ernakulam Shiva) Temple",
        "name_ml": "എറണാകുളത്തപ്പൻ ക്ഷേത്രം",
        "deity": "shiva", "district": "Ernakulam", "town": "Ernakulam",
        "lat": 9.9685, "lng": 76.2822,
        "famous_for": "the city's guardian Mahadeva; steadiness through Shani seasons",
        "vazhipadu": ["dhara", "koovala mala", "vilakku"],
        "reviewed": True,
    },
    {
        "id": "ekm-chottanikkara",
        "name": "Chottanikkara Bhagavathy Temple",
        "name_ml": "ചോറ്റാനിക്കര ഭഗവതി ക്ഷേത്രം",
        "deity": "devi", "district": "Ernakulam", "town": "Chottanikkara",
        "lat": 9.9332, "lng": 76.3912,
        "famous_for": "Devi worshipped for mental peace and healing of the mind (guruthi pooja)",
        "vazhipadu": ["guruthi pooja", "bhajanam irikkal", "archana"],
        "reviewed": True,
    },
    {
        "id": "ekm-poornathrayeesa",
        "name": "Sree Poornathrayeesa Temple",
        "name_ml": "ശ്രീ പൂർണ്ണത്രയീശ ക്ഷേത്രം",
        "deity": "vishnu", "district": "Ernakulam", "town": "Tripunithura",
        "lat": 9.945, "lng": 76.3421,
        "famous_for": "Santana Gopala Murthy; blessing of children and family continuity",
        "vazhipadu": ["santana gopala archana", "palpayasam"],
        "reviewed": True,
    },
    {
        "id": "ekm-thiruvairanikulam",
        "name": "Thiruvairanikulam Mahadeva Temple",
        "name_ml": "തിരുവൈരാണിക്കുളം മഹാദേവ ക്ഷേത്രം",
        "deity": "devi", "district": "Ernakulam", "town": "Sreemoolanagaram",
        "lat": 10.1198, "lng": 76.4168,
        "famous_for": "Parvathy nada opens only 12 days a year; mangalya bhagya (timely marriage) prayers",
        "vazhipadu": ["swayamvara pushpanjali", "umamaheswara pooja"],
        "reviewed": True,
    },
    {
        "id": "ekm-thrikkakara",
        "name": "Thrikkakara Vamanamoorthy Temple",
        "name_ml": "തൃക്കാക്കര വാമനമൂർത്തി ക്ഷേത്രം",
        "deity": "vishnu", "district": "Ernakulam", "town": "Thrikkakara",
        "lat": 10.0355, "lng": 76.3295,
        "famous_for": "Vamana (of Onam legend); humility, fresh starts, and prosperity",
        "vazhipadu": ["archana", "palpayasam"],
        "reviewed": True,
    },
    {
        "id": "ekm-thottuva-dhanwantari",
        "name": "Thottuva Sree Dhanwanthari Temple",
        "name_ml": "തോട്ടുവ ശ്രീ ധന്വന്തരി ക്ഷേത്രം",
        "deity": "dhanwantari", "district": "Ernakulam", "town": "Thottuva (near Perumbavoor)",
        "lat": 10.1786, "lng": 76.4931,
        "famous_for": "Dhanwantari (lord of healing); prayers for recovery from illness",
        "vazhipadu": ["mukkudi nivedyam", "dhanwantari homam"],
        "reviewed": True,
    },
    # ---- Thrissur ----
    {
        "id": "tsr-guruvayur",
        "name": "Guruvayur Sree Krishna Temple",
        "name_ml": "ഗുരുവായൂർ ശ്രീകൃഷ്ണ ക്ഷേത്രം",
        "deity": "krishna", "district": "Thrissur", "town": "Guruvayur",
        "lat": 10.5947, "lng": 76.0394,
        "famous_for": "Guruvayurappan; thulabharam, wedding blessings, and santana gopala prayers for children",
        "vazhipadu": ["thulabharam", "palpayasam", "krishnanattam", "prasadamoottu"],
        "reviewed": True,
    },
    {
        "id": "tsr-vadakkunnathan",
        "name": "Vadakkunnathan Temple",
        "name_ml": "വടക്കുന്നാഥൻ ക്ഷേത്രം",
        "deity": "shiva", "district": "Thrissur", "town": "Thrissur",
        "lat": 10.5245, "lng": 76.2145,
        "famous_for": "ancient Shiva shrine at the heart of Thrissur Pooram; inner steadiness",
        "vazhipadu": ["dhara", "koovala mala"],
        "reviewed": True,
    },
    {
        "id": "tsr-kodungallur-devi",
        "name": "Kodungallur Sree Kurumba Bhagavathy Temple",
        "name_ml": "കൊടുങ്ങല്ലൂർ ശ്രീ കുറുംബ ഭഗവതി ക്ഷേത്രം",
        "deity": "devi", "district": "Thrissur", "town": "Kodungallur",
        "lat": 10.2269, "lng": 76.1983,
        "famous_for": "one of Kerala's oldest Bhagavathy temples; courage and protection",
        "vazhipadu": ["pattum thalika", "archana"],
        "reviewed": True,
    },
    {
        "id": "tsr-nelluvai-dhanwantari",
        "name": "Nelluvai Sree Dhanwanthari Temple",
        "name_ml": "നെല്ലുവായ് ശ്രീ ധന്വന്തരി ക്ഷേത്രം",
        "deity": "dhanwantari", "district": "Thrissur", "town": "Nelluvai (Wadakkanchery)",
        "lat": 10.6817, "lng": 76.1757,
        "famous_for": "ancient Dhanwantari shrine; healing and health prayers (mukkudi)",
        "vazhipadu": ["mukkudi nivedyam", "abhishekam"],
        "reviewed": True,
    },
    {
        "id": "tsr-koodalmanikyam",
        "name": "Koodalmanikyam Temple",
        "name_ml": "കൂടൽമാണിക്യം ക്ഷേത്രം",
        "deity": "vishnu", "district": "Thrissur", "town": "Irinjalakuda",
        "lat": 10.3466, "lng": 76.2011,
        "famous_for": "Bharata (Sangameshwara); rare shrine, prayers for stomach ailments and steadfastness",
        "vazhipadu": ["brinjal (vazhuthananga) nivedyam", "archana"],
        "reviewed": True,
    },
    {
        "id": "tsr-pambummekkattu",
        "name": "Pambummekkattu Mana Nagaraja Shrine",
        "name_ml": "പാമ്പുമേക്കാട്ട് മന",
        "deity": "naga", "district": "Thrissur", "town": "Mala",
        "lat": 10.2575, "lng": 76.2652,
        "famous_for": "famed Namboothiri mana for sarpa dosha relief and Rahu-Ketu preethi",
        "vazhipadu": ["noorum palum", "sarpa pooja"],
        "reviewed": True,
    },
    # ---- Palakkad ----
    {
        "id": "pkd-kalpathy",
        "name": "Kalpathy Sree Viswanatha Swamy Temple",
        "name_ml": "കൽപ്പാത്തി ശ്രീ വിശ്വനാഥസ്വാമി ക്ഷേത്രം",
        "deity": "shiva", "district": "Palakkad", "town": "Kalpathy",
        "lat": 10.7949, "lng": 76.6478,
        "famous_for": "Kashi of Kerala (Ratholsavam); Shiva worship for maturity through hard seasons",
        "vazhipadu": ["dhara", "abhishekam"],
        "reviewed": True,
    },
    {
        "id": "pkd-hemambika",
        "name": "Hemambika (Emoor Bhagavathy) Temple",
        "name_ml": "ഹേമാംബിക ക്ഷേത്രം (ഏമൂർ ഭഗവതി)",
        "deity": "devi", "district": "Palakkad", "town": "Kallekulangara",
        "lat": 10.8081, "lng": 76.6419,
        "famous_for": "Kaipathi (hands-only) Devi; blessings for family and studies",
        "vazhipadu": ["archana", "vilakku"],
        "reviewed": True,
    },
    {
        "id": "pkd-thiruvilwamala",
        "name": "Thiruvilwamala Vilwadrinatha Temple",
        "name_ml": "തിരുവില്വാമല വില്വാദ്രിനാഥ ക്ഷേത്രം",
        "deity": "vishnu", "district": "Palakkad", "town": "Thiruvilwamala",
        "lat": 10.7407, "lng": 76.4309,
        "famous_for": "Rama and Lakshmana shrines on the hill; pitru rites at nearby Ivar Madam",
        "vazhipadu": ["archana", "bali tharpanam (Ivar Madam)"],
        "reviewed": True,
    },
    # ---- Malappuram ----
    {
        "id": "mpm-kadampuzha",
        "name": "Kadampuzha Bhagavathy Temple",
        "name_ml": "കടമ്പുഴ ഭഗവതി ക്ഷേത്രം",
        "deity": "devi", "district": "Malappuram", "town": "Kadampuzha",
        "lat": 10.9439, "lng": 76.0435,
        "famous_for": "muttarukkal (coconut offering) for breaking stubborn obstacles",
        "vazhipadu": ["muttarukkal", "pushpanjali"],
        "reviewed": True,
    },
    {
        "id": "mpm-thirunavaya",
        "name": "Thirunavaya Navamukunda Temple",
        "name_ml": "തിരുനാവായ നാവാമുകുന്ദ ക്ഷേത്രം",
        "deity": "vishnu", "district": "Malappuram", "town": "Thirunavaya",
        "lat": 10.8637, "lng": 75.9817,
        "famous_for": "bali tharpanam on the Bharathappuzha for peace of ancestors",
        "vazhipadu": ["bali tharpanam", "archana"],
        "reviewed": True,
    },
    {
        "id": "mpm-thirumandhamkunnu",
        "name": "Thirumandhamkunnu Bhagavathy Temple",
        "name_ml": "തിരുമാന്ധാംകുന്ന് ഭഗവതി ക്ഷേത്രം",
        "deity": "devi", "district": "Malappuram", "town": "Angadipuram",
        "lat": 10.9801, "lng": 76.2016,
        "famous_for": "ancestral Devi of many families; family welfare and protection",
        "vazhipadu": ["pattum thalika", "archana"],
        "reviewed": True,
    },
    # ---- Kozhikode ----
    {
        "id": "kkd-tali",
        "name": "Tali Mahadeva Temple",
        "name_ml": "തളി മഹാദേവ ക്ഷേത്രം",
        "deity": "shiva", "district": "Kozhikode", "town": "Kozhikode",
        "lat": 11.2477, "lng": 75.7876,
        "famous_for": "the Zamorins' Shiva temple; steadiness and dignity through trials",
        "vazhipadu": ["dhara", "vilakku"],
        "reviewed": True,
    },
    {
        "id": "kkd-lokanarkavu",
        "name": "Lokanarkavu Bhagavathy Temple",
        "name_ml": "ലോകനാർകാവ് ഭഗവതി ക്ഷേത്രം",
        "deity": "devi", "district": "Kozhikode", "town": "Vadakara",
        "lat": 11.5981, "lng": 75.6197,
        "famous_for": "Durga of the ballads (vadakkan pattukal); courage and protection",
        "vazhipadu": ["archana", "vilakku pooja"],
        "reviewed": True,
    },
    # ---- Wayanad ----
    {
        "id": "wyd-thirunelli",
        "name": "Thirunelli Maha Vishnu Temple",
        "name_ml": "തിരുനെല്ലി മഹാവിഷ്ണു ക്ഷേത്രം",
        "deity": "vishnu", "district": "Wayanad", "town": "Thirunelli",
        "lat": 11.9117, "lng": 75.9961,
        "famous_for": "Kashi of the South; bali tharpanam at Papanasini for peace of ancestors",
        "vazhipadu": ["bali tharpanam (Papanasini)", "archana"],
        "reviewed": True,
    },
    {
        "id": "wyd-valliyoorkavu",
        "name": "Valliyoorkavu Bhagavathy Temple",
        "name_ml": "വള്ളിയൂർക്കാവ് ഭഗവതി ക്ഷേത്രം",
        "deity": "devi", "district": "Wayanad", "town": "Mananthavady",
        "lat": 11.8044, "lng": 76.03,
        "famous_for": "Devi in three forms; protection and family welfare",
        "vazhipadu": ["archana", "vilakku"],
        "reviewed": True,
    },
    # ---- Kannur ----
    {
        "id": "knr-rajarajeshwara",
        "name": "Rajarajeshwara Temple",
        "name_ml": "രാജരാജേശ്വര ക്ഷേത്രം",
        "deity": "shiva", "district": "Kannur", "town": "Taliparamba",
        "lat": 12.0483, "lng": 75.3558,
        "famous_for": "one of Kerala's most sacred Shiva temples; resolving weighty, long-running matters",
        "vazhipadu": ["neyyamrithu", "dhara"],
        "reviewed": True,
    },
    {
        "id": "knr-parassinikkadavu",
        "name": "Parassinikkadavu Sree Muthappan Temple",
        "name_ml": "പറശ്ശിനിക്കടവ് ശ്രീ മുത്തപ്പൻ ക്ഷേത്രം",
        "deity": "vishnu", "district": "Kannur", "town": "Parassinikkadavu",
        "lat": 11.9825, "lng": 75.4022,
        "famous_for": "Muthappan (Theyyam) worship open to all; livelihood and protection of the working person",
        "vazhipadu": ["payankutti", "vellattam/thiruvappana darshanam"],
        "reviewed": True,
    },
    {
        "id": "knr-madayi-kavu",
        "name": "Madayi Kavu (Thiruvarkadu Bhagavathy) Temple",
        "name_ml": "മാടായിക്കാവ് (തിരുവർകാട് ഭഗവതി)",
        "deity": "devi", "district": "Kannur", "town": "Pazhayangadi",
        "lat": 12.0348, "lng": 75.2613,
        "famous_for": "ancient Bhadrakali kavu; protection and removal of persistent troubles",
        "vazhipadu": ["raktha pushpanjali", "guruthi"],
        "reviewed": True,
    },
    # ---- Kasaragod ----
    {
        "id": "ksd-madhur-ganapathi",
        "name": "Madhur Sree Madanantheshwara Siddhivinayaka Temple",
        "name_ml": "മധൂർ ശ്രീ മദനന്തേശ്വര സിദ്ധിവിനായക ക്ഷേത്രം",
        "deity": "ganapathi", "district": "Kasaragod", "town": "Madhur",
        "lat": 12.5534, "lng": 75.0101,
        "famous_for": "Siddhivinayaka; udayastamana pooja and appam offering for removing obstacles",
        "vazhipadu": ["appam nivedyam", "ganapathi homam"],
        "reviewed": True,
    },
    {
        "id": "ksd-ananthapura",
        "name": "Ananthapura Lake Temple",
        "name_ml": "അനന്തപുര തടാക ക്ഷേത്രം",
        "deity": "vishnu", "district": "Kasaragod", "town": "Kumbla",
        "lat": 12.5842, "lng": 74.9821,
        "famous_for": "original seat (moolasthanam) of Ananthapadmanabha; lake shrine",
        "vazhipadu": ["archana", "palpayasam"],
        "reviewed": True,
    },
]
