"""Build docs/GROWTH_PLAN_IMPLEMENTATION.pdf — how each shipped part works.

The living implementation companion to GROWTH_PLAN.md: one chapter per part,
covering architecture, tables, endpoints, flows, guardrails, and what is
mocked vs live. Re-run after landing a part to refresh the PDF:

    python scripts/build_growth_pdf.py

Content lives in the CHAPTERS structure below — update it alongside code.
ASCII/latin-1 only (built-in Helvetica); Malayalam strings are transliterated.
"""

import sys
from datetime import date
from pathlib import Path

from fpdf import FPDF

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "GROWTH_PLAN_IMPLEMENTATION.pdf"

ACCENT = (138, 90, 0)
INK = (34, 36, 58)
MUTED = (107, 111, 138)

# ---------------------------------------------------------------------------
# Content. Each chapter: (title, [(heading, body), ...]).
# Body text is plain paragraphs; lines starting with "- " render as bullets,
# lines starting with "  " render in a monospace-ish smaller font (paths).
# ---------------------------------------------------------------------------

CHAPTERS: list[tuple[str, list[tuple[str, str]]]] = [
    (
        "Part 0 -- Platform enablers",
        [
            ("What it is",
             "Four pieces of infrastructure every growth feature depends on. The prod "
             "host (Hugging Face Spaces Docker + Neon Postgres) has no Celery/Redis and "
             "an ephemeral filesystem, so scheduling, media storage, schema migrations "
             "and image rendering all needed platform-level answers first."),
            ("Cron endpoints (scheduling without Celery)",
             "Recurring jobs are token-gated POST endpoints fired by an external "
             "scheduler (GitHub Actions cron / cron-job.org) sending X-Cron-Token.\n"
             "- app/platform/cron_auth.py: CronGuard (constant-time compare; open in dev "
             "when the token is unset, 503 in production when unset)\n"
             "- CronOrAdminGuard accepts EITHER the scheduler's token or an admin's, so "
             "the /admin dashboard can trigger the same jobs manually\n"
             "- Consumers: POST /content/run-daily (Part 1), POST /notifications/run-festivals (Part 3)"),
            ("Object storage",
             "- app/platform/storage.py: a Storage interface with LocalStorage (default, "
             "MOCK_STORAGE=true, files under var/storage/) and R2Storage (Cloudflare R2 "
             "via boto3, lazily imported)\n"
             "- Keys are sanitized against path traversal\n"
             "- GET /media/{key} serves stored objects back with cache headers; with R2 "
             "plus a public bucket URL the route sits unused\n"
             "- Everything generated lands here: share cards, daily cards, premium PDFs"),
            ("Alembic migrations",
             "- migrations/ with an async env.py that resolves the DB URL through the "
             "same settings path as the app\n"
             "- Baseline 6aae47b8b3ce autogenerated from all models\n"
             "- scripts/migrate.py: stamps the baseline when it finds a pre-Alembic DB "
             "(the live Neon), otherwise upgrades to head; the Dockerfile CMD runs it "
             "before uvicorn so the schema is current before traffic\n"
             "- Every later part added exactly one revision on this chain"),
            ("Card renderer",
             "- app/platform/cards.py: render_card(title, body, footer, template, branding) -> PNG bytes\n"
             "- Templates: feed 1080x1350, story 1080x1920; gradient background, "
             "pixel-width wrapping, auto-shrinking body\n"
             "- Malayalam: assets/fonts/NotoSansMalayalam-Regular.ttf ships in the repo "
             "(the Google Fonts build -- script-only builds lack Latin); shaping needs "
             "libraqm, bundled in the Linux Pillow wheel (Windows dev renders degraded "
             "conjuncts; prod is correct)\n"
             "- Branding dataclass parameterizes colors/name for Part 4 white-label"),
        ],
    ),
    (
        "Part 1 -- Content Engine",
        [
            ("What it is",
             "Every morning, one generated 'content pack': a WhatsApp Channel message, "
             "a Facebook post, an Instagram Reel script and a YouTube Short script, plus "
             "rendered share cards -- drafted by the LLM, screened for tone, and held "
             "for human approval in /admin before anything publishes."),
            ("Table: content_posts",
             "- One row per (day, platform) -- unique constraint makes the cron idempotent\n"
             "- Lifecycle: draft -> approved -> published | failed\n"
             "- media_key points at the day's rendered card in storage\n"
             "- external_id records what the platform API returned on publish"),
            ("Pipeline (app/modules/content/pipeline.py)",
             "1. Gather: panchangam (astrology_engine) + a knowledge nugget about the "
             "day's nakshatram (knowledge corpus)\n"
             "2. Draft per platform via content/llm.py -- mirrors chat's provider "
             "resolution (Sarvam -> OpenAI -> mock) with the two Sarvam quirks: "
             "reasoning_effort=low and one doubled-budget retry on empty\n"
             "3. Screen EVERY draft with tone_safety.screen_reply; one corrective "
             "retry, then the hand-written compliant fallback -- public copy is never "
             "published unscreened\n"
             "4. Render feed+story cards into storage\n"
             "5. Persist as draft"),
            ("Endpoints",
             "- POST /content/run-daily (cron OR admin token; idempotent)\n"
             "- GET /content/posts?day=  |  POST /content/posts/{id}/approve (accepts an "
             "inline body edit)  |  POST /content/posts/{id}/publish (admin token)\n"
             "- Publish is refused unless status=approved -- human review is a hard gate"),
            ("Publishers (content/publishers.py)",
             "- wa_channel: rides whatsapp.publish_to_channel -- the AI disclosure and "
             "opt-out footer are appended IN CODE there; mock BSP until the first live "
             "send is approved\n"
             "- fb_post / ig_reel (Meta Graph API) and yt_short (YouTube Data API): "
             "mocked stubs until those API apps exist; a failed send marks the row "
             "'failed' and shows in /admin\n"
             "- Admin UI: the Content tab (date picker, generate, card previews, inline "
             "edit, approve, publish) plus an Events panel showing the named metrics counters"),
        ],
    ),
    (
        "Part 2 -- Virality (share cards + referral loop)",
        [
            ("What it is",
             "Every good moment inside Tara can leave Tara as a branded image, and "
             "sharing is rewarded: share link -> friend registers -> chart computed -> "
             "referral activates -> at the threshold the referrer's premium report unlocks."),
            ("Table: share_cards",
             "- kind=personal: opaque slug (not enumerable), tone-screened BEFORE "
             "rendering -- an image cannot be redacted once it leaves the app\n"
             "- kind=daily: deterministic slug daily-{date}-{index}, rendered lazily on "
             "first request and cached in storage (27 nakshatra cards per day)\n"
             "- hits: durable landing-page view counter (share-click metric)"),
            ("Tables: referral_codes + referrals",
             "- referral_codes: one 8-char code per user (unambiguous alphabet -- no "
             "0/O/1/I/L -- survives being read aloud); reward_granted_at set at the threshold\n"
             "- referrals: one row per referred signup, unique per referred user; "
             "status=activated because registration computes the chart in-request "
             "(the plan's definition of real activation, not just signup)"),
            ("Flow + endpoints",
             "- POST /content/cards (session auth): insight -> branded PNG + /s link "
             "whose CTA carries the creator's referral code\n"
             "- GET /content/cards/daily/{nakshatra} (public, cached; name or index 0-26)\n"
             "- GET /s/{slug}: OG-tagged landing page -- the card unfurls in WhatsApp; "
             "CTA = /ui/login?ref=CODE; every view bumps hits\n"
             "- GET /identity/referral: code, share link, progress, reward state\n"
             "- Registration accepts ref (best-effort -- a stale code never fails signup)\n"
             "- UI: share button on chat replies (native share sheet); ?ref= passthrough "
             "on both login pages; admin Referrals tile + funnel numbers"),
            ("Reward",
             "At referral_reward_threshold (default 3) activated referrals, identity "
             "grants a durable premium_report entitlement through commerce (Part 5a), "
             "granted_by=referral -- the same entitlement a purchase creates."),
        ],
    ),
    (
        "Part 5a -- Payments core",
        [
            ("What it is",
             "The money layer: Razorpay orders with a signature-verified webhook, and "
             "an entitlements table that is the SINGLE source of truth for what a user "
             "may use. Feature code checks entitlements, never payment rows."),
            ("Tables: payments + entitlements",
             "- payments: one row per order; integer paise; unique razorpay_order_id; "
             "status created -> paid | failed\n"
             "- entitlements: user_id/org_id, product_key, granted_by "
             "(purchase|referral|admin), source (audit), expires_at (null = forever); "
             "idempotent grants -- a replayed webhook never double-grants"),
            ("Flow",
             "1. POST /commerce/orders {product} -- price comes from the server-side "
             "catalog, the client never sends an amount\n"
             "2. Client-side Razorpay checkout (live) or POST /commerce/orders/{id}/mock-pay "
             "(mock mode only -- the whole unlock flow runs with zero keys)\n"
             "3. Razorpay calls POST /commerce/webhook/razorpay; the body's HMAC-SHA256 "
             "signature is verified (fail-closed live when no secret; skipped in mock); "
             "payment.captured marks paid + grants the entitlement\n"
             "4. GET /commerce/entitlements lists what the user has unlocked"),
            ("Implementation notes",
             "- Razorpay is called over plain httpx with Basic auth -- no SDK dependency\n"
             "- Unknown-order webhooks are acknowledged with 2xx so Razorpay does not "
             "retry forever\n"
             "- create_custom_order supports org-priced things (Part 4b bookings)"),
        ],
    ),
    (
        "Part 5b -- Premium reports",
        [
            ("What it is",
             "The premium jathaka PDF: 4 pages (cover; graha table with calm dosha "
             "framing; vimshottari dasha timeline with the current dasha highlighted; a "
             "gentle year-ahead outlook). Entitlement-gated -- buy it or earn it via referrals."),
            ("Why Pillow, not reportlab",
             "reportlab does no complex-text shaping, so Malayalam conjuncts would "
             "render broken. The report renders image pages through the exact same "
             "font + raqm path as the share cards, then saves them as a multi-page PDF "
             "(Pillow supports PDF output natively)."),
            ("Flow",
             "- POST /commerce/reports/premium: 402 without the premium_report "
             "entitlement, 409 without a computed chart; otherwise renders once per "
             "user per day into storage and returns the /media download URL\n"
             "- Outlook copy is deterministic per dasha lord -- no LLM in the money "
             "path, no doom, no remedies; every page footer carries the agency line"),
        ],
    ),
    (
        "Part 3 -- Temple partnerships",
        [
            ("What it is",
             "Temples become distribution partners: a printed QR opens a genuinely "
             "useful page (panchangam, festivals, vazhipadu), visitors can subscribe to "
             "festival updates on WhatsApp, and temples can embed a panchangam widget "
             "on their own sites."),
            ("Tables",
             "- temple_partners: slug per curated-directory temple (devotional content "
             "stays in the reviewed seed data -- partners cannot edit it)\n"
             "- temple_subscriptions: phone-keyed, unique per (phone, temple); "
             "subscribing IS the WhatsApp opt-in, recorded through the whatsapp "
             "module's consent ledger, never around it\n"
             "- temple_festivals: dated entries partners supply via the admin console\n"
             "- notification_log: one row per (kind, dedupe_key, phone) -- sends happen "
             "exactly once no matter how often the cron fires"),
            ("Public surfaces",
             "- GET /t/{slug}: mobile-first microsite -- today's panchangam, upcoming "
             "festivals, vazhipadu list, Ask-Tara CTA, subscribe form with a "
             "plain-language consent note; ?src=qr visits are counted separately\n"
             "- GET /widget/panchangam?temple={slug}: self-contained iframe page with a "
             "Tara footer link; one static snippet for temple webmasters"),
            ("Admin console + notifications",
             "- POST/GET /temples/partners, POST /temples/partners/{slug}/festivals, "
             "GET /temples/partners/{slug}/qr.png (print-sized QR -> /t/{slug}?src=qr)\n"
             "- POST /notifications/run-festivals (cron-or-admin): festivals exactly "
             "T-3 days out -> one WhatsApp template message per opted-in subscriber\n"
             "- whatsapp.send_template is the ONLY 1:1 send path: opt-in required, 24h "
             "cap (3/day) enforced, AI-disclosure + opt-out footer appended in code"),
        ],
    ),
    (
        "Part 4a -- Tenancy core (white-label)",
        [
            ("What it is",
             "An astrologer gets their own branded Tara at /a/{handle}/ui -- same chat "
             "brain, same guardrails, their name/colors/persona flavor."),
            ("Table: orgs + users.org_id",
             "- orgs: handle (URL slug, reserved names blocked), name, logo_key, theme "
             "colors, persona_overlay (capped 1200 chars), plan, owner_user_id, billing "
             "fields (Part 5c)\n"
             "- users.org_id: nullable -- null means Tara-direct; set when someone "
             "registers from /a/{handle}/login (best-effort like ref)"),
            ("The overlay rule (non-negotiable)",
             "The persona overlay adds flavor, never removes safety. OrgsService wraps "
             "tenant text in a preamble stating it may adjust name/greeting/flavor ONLY "
             "and can never override the rules; chat appends it AFTER tone_safety's "
             "system prompt. The crisis screen, reply screen and corrective-retry flow "
             "are identical for every tenant."),
            ("Surfaces",
             "- POST/GET /orgs (admin), GET /orgs/{handle}/public (branding, no auth)\n"
             "- /a/{handle}/ui and /a/{handle}/login: the SAME static pages with a "
             "branding snippet injected (title, CSS variables, brand text, org tag "
             "stored for registration)"),
        ],
    ),
    (
        "Part 4b -- Booking system",
        [
            ("What it is",
             "Consultation booking on the org's white-label site: the astrologer "
             "defines weekly windows, customers book concrete times, paid slots ride "
             "the commerce order flow."),
            ("Tables",
             "- availability_slots: weekly windows (weekday, minutes-from-midnight "
             "start/end, duration, price in paise; 0 = free consult)\n"
             "- bookings: unique (org_id, starts_at) -- double-booking is impossible at "
             "the DB; cancelled rows are revived on rebook so freed times stay bookable\n"
             "- Status: pending -> confirmed -> completed | cancelled"),
            ("Flow",
             "1. Owner: POST /orgs/{handle}/booking/slots (org-owner auth)\n"
             "2. Anyone: GET /orgs/{handle}/booking/availability?day= -- windows sliced "
             "into open start times, minus booked\n"
             "3. Customer: POST /orgs/{handle}/booking {starts_at} -- free slots confirm "
             "instantly; paid slots return a commerce order (price set server-side from "
             "the slot) and stay pending until the payment captures\n"
             "4. Confirmation reconciles lazily on read (no webhook coupling); a failed "
             "payment auto-cancels; confirmed bookings trigger a best-effort WhatsApp "
             "confirmation through the guarded send_template path\n"
             "5. Cancel: the booking's user or the org owner"),
        ],
    ),
    (
        "Part 4c -- CRM-lite (astrologer dashboard)",
        [
            ("What it is",
             "/a/{handle}/dashboard: the astrologer's customer list, each customer's "
             "computed chart (their prep work done for them), booking history, private "
             "notes, and -- only with explicit customer consent -- chat transcripts."),
            ("Table: customer_notes + users.transcript_consent",
             "- customer_notes: org-scoped private notes, visible only to the owner\n"
             "- users.transcript_consent (default false): ONLY the customer can flip it "
             "(POST /identity/transcript-consent); the astrologer can never grant "
             "themselves access -- the transcript endpoint returns 403 until then"),
            ("API (all org-owner gated)",
             "- GET /orgs/{handle}/crm/customers -- display fields only, no birth data\n"
             "- GET .../customers/{id}/chart | /bookings | /notes (+POST) | /transcript\n"
             "- Another org's customer returns 404, never a leak"),
        ],
    ),
    (
        "Part 5c -- SaaS subscriptions",
        [
            ("What it is",
             "The billing layer for white-label orgs: starter/pro plans on Razorpay "
             "Subscriptions, plan gates, and dunning that soft-locks growth features "
             "without ever deleting data."),
            ("Model",
             "- orgs.billing_status: trial (default, full features) -> active (paying) "
             "-> past_due (renewal failed)\n"
             "- PLAN_LIMITS per plan: customer cap (starter 25 / pro 5000), booking flag\n"
             "- Subscription events from the shared Razorpay webhook route to "
             "OrgsService.apply_subscription_event: charged/activated/resumed -> "
             "active; halted/paused/cancelled -> past_due"),
            ("Dunning = soft-lock",
             "past_due blocks NEW bookings (409) and NEW customer attachments "
             "(signups still succeed as Tara-direct -- never bounced), while the CRM, "
             "existing bookings and all data stay readable. Recovery (next successful "
             "charge) unlocks instantly."),
            ("Surfaces",
             "- GET /orgs/{handle}/billing + POST .../billing/subscribe (owner; mock "
             "mints sub_mock_* and activates immediately)\n"
             "- POST /orgs/{handle}/plan (admin ops lever)\n"
             "- Live mode needs razorpay_plan_id_starter/pro in settings"),
        ],
    ),
    (
        "Going live -- what is mocked vs real",
        [
            ("Real today (no external accounts needed)",
             "- The full review workflow, share cards, landing pages, referrals, "
             "entitlements, premium PDFs, temple microsites/QRs/widgets, white-label "
             "chat, bookings, CRM, billing state machine -- all tested end-to-end "
             "(197 tests) against mocks that mirror the live contracts"),
            ("Blocked on external accounts (not on code)",
             "- Gupshup (or other BSP): flips MOCK_WHATSAPP -- WhatsApp Channel "
             "publishing (Part 1) and 1:1 sends (Parts 3/4b); FIRST live send needs "
             "human approval per AGENTS.md\n"
             "- Meta developer app: fb_post / ig_reel publishers\n"
             "- YouTube API + a video pipeline: yt_short\n"
             "- Razorpay account: live orders/webhooks/subscriptions "
             "(razorpay_key_id/secret, webhook secret, plan ids)\n"
             "- Cloudflare R2 credentials: durable media (mock_storage=false)"),
            ("Deploy checklist",
             "- Set CRON_TOKEN + ADMIN_TOKEN in the Space secrets\n"
             "- Point a scheduler (GitHub Actions cron) at POST /content/run-daily and "
             "POST /notifications/run-festivals each morning with X-Cron-Token\n"
             "- Set PUBLIC_BASE_URL=https://arunjith-tara.hf.space so share links and "
             "og:image URLs are absolute\n"
             "- scripts/migrate.py runs at boot: the live Neon DB stamps the baseline "
             "then applies the 6 growth revisions in order\n"
             "- Eyeball one rendered card + one premium PDF on the deployed Space "
             "(Windows dev lacks raqm; the Docker image shapes Malayalam correctly)"),
        ],
    ),
]

INTRO = (
    "How the five growth initiatives from GROWTH_PLAN.md were implemented on the "
    "Tara modular monolith (FastAPI + Postgres + Alembic + the platform layer). "
    "Build order followed the dependency graph: "
    "0 -> 1 -> 2 -> 5a -> 5b -> 3 -> 4a -> 4b -> 4c -> 5c. "
    "Every part landed with tests (197 passing at 5c), metrics counters surfaced "
    "in the /admin Events panel, MOCK_* flags for every external integration, "
    "and the cross-cutting guardrails: every public text passes the tone_safety "
    "screen, every send-to-user path goes through consent + throttle, and no "
    "guardrail is overridable by tenants."
)


class GrowthPdf(FPDF):
    def header(self):
        if self.page_no() == 1:
            return
        self.set_font("helvetica", "I", 8)
        self.set_text_color(*MUTED)
        self.cell(0, 6, "Tara Growth Plan -- Implementation", align="L")
        self.cell(0, 6, f"regenerated {date.today().isoformat()}", align="R",
                  new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def footer(self):
        self.set_y(-14)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(*MUTED)
        self.cell(0, 8, f"{self.page_no()}", align="C")

    def chapter(self, title: str, sections: list[tuple[str, str]]):
        self.add_page()
        self.set_font("helvetica", "B", 17)
        self.set_text_color(*ACCENT)
        self.multi_cell(0, 9, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*ACCENT)
        self.set_line_width(0.6)
        self.line(self.l_margin, self.get_y() + 1, self.l_margin + 60, self.get_y() + 1)
        self.ln(6)
        for heading, body in sections:
            self.set_font("helvetica", "B", 11.5)
            self.set_text_color(*INK)
            self.multi_cell(0, 6, heading, new_x="LMARGIN", new_y="NEXT")
            self.ln(0.5)
            self.set_font("helvetica", "", 10)
            for raw in body.split("\n"):
                line = raw.rstrip()
                if line.startswith("- "):
                    x = self.get_x()
                    self.set_x(x + 4)
                    self.set_text_color(*ACCENT)
                    self.cell(4, 5.4, chr(149))
                    self.set_text_color(*INK)
                    self.multi_cell(0, 5.4, line[2:], new_x="LMARGIN", new_y="NEXT")
                    self.set_x(x)
                else:
                    self.set_text_color(*INK)
                    self.multi_cell(0, 5.4, line, new_x="LMARGIN", new_y="NEXT")
            self.ln(3.5)


def build() -> Path:
    pdf = GrowthPdf(format="A4")
    pdf.set_auto_page_break(True, margin=18)
    pdf.set_margins(20, 16, 20)

    # Cover
    pdf.add_page()
    pdf.ln(48)
    pdf.set_font("helvetica", "B", 30)
    pdf.set_text_color(*ACCENT)
    pdf.multi_cell(0, 13, "Tara Growth Plan", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "B", 18)
    pdf.set_text_color(*INK)
    pdf.multi_cell(0, 10, "Implementation -- how every part works", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)
    pdf.set_font("helvetica", "", 10.5)
    pdf.set_text_color(*MUTED)
    pdf.multi_cell(0, 5.8, INTRO, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(*INK)
    for i, (title, _) in enumerate(CHAPTERS, 1):
        pdf.cell(8, 6, f"{i}.")
        pdf.multi_cell(0, 6, title, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)
    pdf.set_font("helvetica", "I", 9)
    pdf.set_text_color(*MUTED)
    pdf.multi_cell(
        0, 5,
        f"Generated {date.today().isoformat()} by scripts/build_growth_pdf.py "
        "-- update the CHAPTERS content there and re-run after each part lands.",
        new_x="LMARGIN", new_y="NEXT",
    )

    for title, sections in CHAPTERS:
        pdf.chapter(title, sections)

    OUT.parent.mkdir(exist_ok=True)
    pdf.output(str(OUT))
    return OUT


if __name__ == "__main__":
    path = build()
    size_kb = path.stat().st_size // 1024
    sys.stdout.write(f"wrote {path} ({size_kb} KB)\n")
